//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAnalytics.Utils.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResponseLocalized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResponseLocalized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientAnalytics.Utils.Localization.ApiResponseLocalized", typeof(ApiResponseLocalized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to decode User ID from token.
        /// </summary>
        public static string AuthError_DecodeJwt_Parse {
            get {
                return ResourceManager.GetString("AuthError_DecodeJwt_Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find user with id: {0}.
        /// </summary>
        public static string AuthError_DecodeJwt_UserNotFound {
            get {
                return ResourceManager.GetString("AuthError_DecodeJwt_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the correct authorization.
        /// </summary>
        public static string AuthError_Unauthorized {
            get {
                return ResourceManager.GetString("AuthError_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the correct Super Admin authorization.
        /// </summary>
        public static string AuthError_Unauthorized_SuperAdmin {
            get {
                return ResourceManager.GetString("AuthError_Unauthorized_SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string AuthError_UserNotFound {
            get {
                return ResourceManager.GetString("AuthError_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password. This password has been leaked before. Choose a different password..
        /// </summary>
        public static string AuthError_WeakPassword_IsHashLeaked {
            get {
                return ResourceManager.GetString("AuthError_WeakPassword_IsHashLeaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password. Password length must be more than {0} characters and contain special characters..
        /// </summary>
        public static string AuthError_WeakPassword_Validation {
            get {
                return ResourceManager.GetString("AuthError_WeakPassword_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Password.
        /// </summary>
        public static string AuthError_WrongPassword {
            get {
                return ResourceManager.GetString("AuthError_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate Authorization on the request headers.
        /// </summary>
        public static string HeaderError_Authorization {
            get {
                return ResourceManager.GetString("HeaderError_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate blood pressure record with id: {0}.
        /// </summary>
        public static string PatientBloodPressureError_NotFound {
            get {
                return ResourceManager.GetString("PatientBloodPressureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is forbidden from viewing and modifying patient with id: {0}.
        /// </summary>
        public static string PatientError_Forbidden {
            get {
                return ResourceManager.GetString("PatientError_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate patient with id: {0}.
        /// </summary>
        public static string PatientError_NotFound {
            get {
                return ResourceManager.GetString("PatientError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate height record with id: {0}.
        /// </summary>
        public static string PatientHeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientHeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate temperature record with id: {0}.
        /// </summary>
        public static string PatientTemperatureError_NotFound {
            get {
                return ResourceManager.GetString("PatientTemperatureError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate weight record with id: {0}.
        /// </summary>
        public static string PatientWeightError_NotFound {
            get {
                return ResourceManager.GetString("PatientWeightError_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address {0} already taken.
        /// </summary>
        public static string RepeatedError_Email {
            get {
                return ResourceManager.GetString("RepeatedError_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} already taken.
        /// </summary>
        public static string RepeatedError_Username {
            get {
                return ResourceManager.GetString("RepeatedError_Username", resourceCulture);
            }
        }
    }
}
